# Generated by Django 2.0.5 on 2019-04-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0004_auto_20190429_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientposts_model',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
